version: '3.8'

services:
  postgres:
    image: postgres:15-alpine # Use the desired PostgreSQL version
    container_name: dovlink_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Expose PostgreSQL on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data: